# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d32c7070e9c0d6169337f126f8cbe9fb968ce9fcd9bb3045f0b980927138b5f0a843ccedbf11714e740ddfd033204962377c6f90cee126db8c81b0701125016f

test:
  secret_key_base: a72a2aeed36de65f2621a8ba4862faaf7ec732ed93b9be9b5e8e1ec453d3d7f56006b5416d0c160a542b5108d70294ecac2d1575f5bbc19cb7040ba0242d817f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
